openapi: 3.1.0
info:
  title: Shopping Cart API (REST API Murni)
  description: Dokumentasi API untuk Shopping Cart.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ProductID:
                      type: integer
                      example: 1
                    Name:
                      type: string
                      example: "Laptop"
                    Price:
                      type: number
                      example: 999.99
